#!/usr/bin/env sh

# Diretório de backup
backup_path="/home/alessandro"

# Destino do backup
storage="/home/alessandro/Dados/backup"

# Formato do arquivo
date_format=$(date "+%d-%m-%Y_%H-%M")
final_archive="backup-$date_format.tar.gz"

# Onde o log será armazenado?
log_file="/var/log/daily-backup.log"

#######################
#       TESTE         #
#######################

# Checando se o diretório de destino existe
if [ ! -d "$storage" ]; then
    printf "Directory %s does not exist. CHECK IT.\n" "$storage" | tee -a "$log_file"
    exit 1
fi

#######################
#   Início de backup  #
#######################

# Executando o backup, incluindo apenas os diretórios especificados
if tar -czSpf "$storage/$final_archive" \
    -C "$backup_path" Documentos Downloads Imagens Vídeos Músicas Projeto Shell-scripts; then
    printf "Backup successful: %s/%s\n" "$storage" "$final_archive" | tee -a "$log_file"
else
    printf "Backup failed.\n" | tee -a "$log_file"
    exit 1
fi
