#!/usr/bin/env bash

#Author: Alessandro Braun ablenda@gmail.com
#Discribe: Script para instalação do Neovim + Spacevim.
#Version: 0.1
#License: MIT License

VERMELHO='\e[1;91m'
VERDE='\e[1;92m'
NC='\e[0m'

#Neovim está instalado?
if [[ ! -x $(which neovim) ]]; then
  echo -e "${VERMELHO}[erro]*** Programa Neovim não instalado ***${NC}"
  echo -e "${VERDE}[Info]*** Instalando o Neovim ***${NC}"
  apt update &> /dev/null
  apt install neovim -y &> /dev/null
else
  echo -e "${VERDE}[Info]*** Progrma Neovim já está instalado ***${NC}"
fi
#Curl está instalado?
if [[ ! -x $(which curl) ]]; then
    echo -e "${VERMELHO}[erro]*** Programa curl não instalado ***${NC}"
    echo -e "${VERDE}[Info]*** Instalando o curl ***${NC}"
    apt install curl -y &> /dev/null
else
    echo -e "${VERDE}[Info]*** Programa curl já está instalado ***${NC}"
fi
#Instalação do Spacevim    
    echo -e "${VERDE}[Info]*** Instalando o Spacevim ***${NC}"
    curl -sLf https://spacevim.org/install.sh | bash -s -- --install Neovim
