#!/usr/bin/env sh

#Author: Alessandro Braun ablenda@gmail.com
#Discribe: Shell script pós instalação Arch Linux.
#Version: 0.1
#License: GPL

#Variáveis
RED='\033[1;31m'
GREEN='\033[1;32m'
BLUE='\033[1;34m'
NC='\033[0m' # No Color
atualizar="pacman -Syu"
instalar="pacman -S"
aur="yay -S"

# Internet conectando?

if ! ping -c 1 8.8.8.8 -q &> /dev/null; then
  echo -e "${RED}   [ERROR] - Seu computador não tem conexão com a Internet. Verifique os cabos e o modem.${NC}";sleep 1
  exit 1
else
  echo -e "${GREEN}   [CHECK] - Conexão com a Internet funcionando normalmente.${NC}";sleep 2
fi

#Atualizar o sistema pacman.

echo -e "${BLUE}   *** ATUALIZAR VIA PACMAN ***${NC}";sleep 1

     $atualizar &> /dev/null

echo -e "${GREEN}   *** ATUALIZAÇÃO CONCLUÍDA ***${NC}";sleep 2

#Instalar o sudo GIT wget base-devel.

echo -e "${BLUE}   *** Instalar git, wget e base-devel ***${NC}";sleep 1

     $instalar sudo git wget base-devel 

#Cadastrar usuário e senha e adicinar em grupos.

echo -e "${BLUE}   *** Criar usuário ***${NC}";sleep 3
     adduser -m alessandro
     passwd alessandro 
echo -e "${BLUE}   *** Adicionar permissões e grupos ***${NC}";sleep 3     
     usermod -aG wheel,storage,power,users alessandro
     echo alessandro ALL=(ALL)ALL >> /etc/sudoers

#Instalar o ufw
echo -e "${BLUE}   *** Instalar UFW ***${NC}";sleep 3
     $instalar ufw -y 
     systemctl enable --now ufw
     ufw enable 

#Instalar o AUR, Snap e Flatpak.
echo -e "${BLUE}   *** Instalar AUR, Snap e Flatpak ***${NC}";sleep 3
     mkdir ~/Downloads
     mkdir ~/Downloads/git
     cd ~/Downloads/git
     git clone https://aur.archlinux.org/yay.git
     cd yay
     makepkg -si -y
     yay -Sy      
     $aur snapd
     $instalar flatpak -y 

#Instalação do xorg, xfce, tilix, sddm, mesa e intel .
echo -e "${BLUE}   *** Instalar xorg, xfce, tilix, sddm, mesa e driver Intel ***${NC}";sleep 3
     $instalar xfce4 xfce4-goodies
     systemctl set-default graphical.target
     $instalar sddm 
     systemctl enable sddm 
     $instalar xorg xorg-server xorg-xinit xorg-utils tilix nemo-fileroller
     $instalar xf86-video-intel mesa mesa-demos   

#Instalação dos demais aplicações.
echo -e "${BLUE}   *** Instalar demais aplicações ***${NC}";sleep 3
     $aur brave-bin  pamac-aur whatsapp-for-linux libreoffice-still-pt-br
     $instalar plank thunderbird -y 

 #Deixar a interface grafice em português.
echo -e "${BLUE}   *** Deixar a interface grafice em português ***${NC}";sleep 1
     locale-gen 
     localectl set-locale pt_BR.UTF-8

#Fim do shell script.

echo -e "${BLUE}   *** Deseja reiniciar o sistema, para atualizações sujam efeito digite \"Sim(s)\" ou \"Não(n)\" para encerar (RECOMENDA-SE REINICIAR)***${NC}"
read CONFIRMA

case $CONFIRMA in 
    "s")
        reboot 
    ;;

    "n")
        reset            
    ;;

    *)
        echo -e "${RED}   *** OPÇÃO INVÁLIDA ***${NC}"
    ;;
esac      