#!/bin/sh

#Author: Alessandro Braun email: ablenda@gmail.com
#Discribe: Ferramenta para limpeza de cache de memória ram.
#Version: 0,3
#License: GPL

  echo "----Esvaziar cache de memória----"

      sudo sync && sudo sysctl -w vm.drop_caches=3
      sudo sync; sudo echo 3 > /proc/sys/vm/drop_caches
      sudo sync; sudo echo 2 > /proc/sys/vm/drop_caches
      sudo sync; sudo echo 1 > /proc/sys/vm/drop_caches

  echo "----Fim do processo____"

